# 課程設定
* 為什麼是 Python?
* 資料科學 ？
* 會有 numpy, jupyter notebook, pandas, scipy, sklearn, tensorflow, keras, opencv
* 實用取向，所以要從原理開始

In [6]:
# 起手式
import numpy as np

建立 ndarray

In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [8]:
x = _

In [21]:
y = np.array([[1.,2,3],[4,5,6]])
y

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

看 ndarray 的第一件事情：  shape , dtype

In [10]:
x.shape

(4,)

In [11]:
y.shape

(2, 3)

In [19]:
x.dtype

dtype('int64')

In [22]:
y.dtype

dtype('float64')

In [12]:
# 建立 0 array
np.zeros_like(y)

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
np.zeros((10,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

這是一堆資料
* 資料有什麼資訊？
* 資料有什麼限制？
* 這些限制有什麼意義？好處？
* 以前碰過什麼類似的東西？
* 可以套用在哪些東西上面？

## Q1:
試試看圖片。
使用
```python
from PIL import Image
# 讀入 PIL Image
img = Image.open('img/Green-Rolling-Hills-Landscape-800px.png')
# 圖片轉成 ndarray
img_array = np.array(img)
# ndarray 轉成 PIL Image
Image.froimg_array(img_array)
```
看看這個圖片的內容, dtype 和 shape 

In [ ]:
# 參考答案
%load q1.py 

### Indexing